<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $cvFileName = 'dummy_cv_' . Str::random(10) . '.pdf';
        $cvFilePath = 'public/storage/cvs/' . $cvFileName;

        if (!Storage::exists('public/storage/cvs')) {
            Storage::makeDirectory('public/storage/cvs');
        }

        // Create a dummy PDF file for the CV
        if (!Storage::exists($cvFilePath)) {
            Storage::put($cvFilePath, $this->generateDummyPdfContent());
        }

        return [
            'name' => $this->faker->name,
            'email' => $this->faker->unique()->safeEmail,
            'password' => bcrypt('password'), // Replace with secure hashing
            'cv' => $cvFilePath,
            'title' => $this->faker->jobTitle,
            'bio' => $this->faker->paragraph,
            'twitter' => $this->faker->url,
            'facebook' => $this->faker->url,
            'linkedin' => $this->faker->url,
        ];
    }

    private function generateDummyPdfContent(): string
    {
        return 'This is a dummy PDF file generated by the factory.';
    }
}
